// <auto-generated />
using System;
using GraduateJobFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduateJobFinder.Migrations
{
    [DbContext(typeof(GraduateJobFinderContext))]
    [Migration("20261007152551_AddProgrammingLanguages")]
    partial class AddProgrammingLanguages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GraduateJobFinder.Models.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobPosting");
                });

            modelBuilder.Entity("GraduateJobFinder.Models.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProgrammingLanguage");
                });

            modelBuilder.Entity("JobPostingProgrammingLanguage", b =>
                {
                    b.Property<int>("JobPostingsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgrammingLanguagesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobPostingsId", "ProgrammingLanguagesId");

                    b.HasIndex("ProgrammingLanguagesId");

                    b.ToTable("JobPostingProgrammingLanguage");
                });

            modelBuilder.Entity("JobPostingProgrammingLanguage", b =>
                {
                    b.HasOne("GraduateJobFinder.Models.JobPosting", null)
                        .WithMany()
                        .HasForeignKey("JobPostingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraduateJobFinder.Models.ProgrammingLanguage", null)
                        .WithMany()
                        .HasForeignKey("ProgrammingLanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
